groups:
  - name: dummy-alert-group
    rules:
#      - alert: SlackTestAlert
#        expr: vector(1)
#        for: 5s
#        labels:
#          severity: test
#        annotations:
#          summary: "🚨 Slack Test Alert"
#          description: "This is a dummy alert to verify Slack integration."

      - alert: High5xxRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0.02
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "🚨 High 5xx Error Rate"
          description: "More than 2% of requests are failing with 5xx in the last 1m."

      - alert: AbnormalTaskSpike
        expr: increase(deploymate_tasks_total[1m]) > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "🔥 Sudden Spike in Task Creation"
          description: "DeployMate created >20 tasks in 1 minute. Investigate unusual behavior."
